# Generated by Django 4.2.16 on 2024-09-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(default='Welcome to Our Website', max_length=255)),
                ('sub_heading', models.CharField(default='Discover Amazing Content', max_length=255)),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_link', models.URLField(default='https://example.com')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
